### ISSUE TITLE
Explore NFT's keeps running with no result

### ISSUE THREAD

**Issue by ditholease** [chrisstef/polyplace#3]
I deployed the gitcode to Gitpod and run the front end. 
Mintig works.
Show NFt's for sale too.
But running "Explore NFT's get stuck.
Any help?

**Comment by chrisstef** [comment]
Its most likely an error coming from the Context. What us the error message you are getting?

**Comment by ditholease** [comment]
Unhandled Runtime Error
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.3)

Call Stack
Logger.makeError
node_modules/@ethersproject/logger/lib.esm/index.js (219:0)
Logger.throwError
node_modules/@ethersproject/logger/lib.esm/index.js (228:0)
JsonRpcProvider.eval
node_modules/@ethersproject/providers/lib.esm/json-rpc-provider.js (357:0)
Generator.throw
<anonymous>
rejected
node_modules/@ethersproject/providers/lib.esm/json-rpc-provider.js (6:41)

**Comment by ditholease** [comment]
Solved the above issue :) New issue occuring
Unhandled Runtime Error
Error: Image is missing required "src" property. Make sure you pass "src" in props to the `next/image` component. Received: {}

Source
pages/index.js (30:8) @ eval

  28 |         setNfts(items);
  29 |         setNftsCopy(items);
> 30 |         setIsLoading(false);
     |        ^
  31 |       });
  32 |   }, []);
  33 |

**Comment by chrisstef** [comment]
If you've succesfully loaded up the home page, and display the nfts locally, it should be ok. The above error occurs because there is propably no nft to display and therefore no image source (`src=''`).

Please let me know if you render the nft's locally.

**Comment by ditholease** [comment]
Thanks for your reply.
It is working now. 
I changed  const provider = new ethers.providers.JsonRpcProvider('https://polygon-mumbai.g.alchemy.com/v2/aT46mujHo45399eX-fWp9mucSwWW6iuA');
to
    const connection = await web3Modal.connect();
    const provider = new ethers.providers.Web3Provider(connection);
 So, It will wait for a MetaMAsk connection first.
Then in loads with no error anymore.

**Comment by chrisstef** [comment]
Good catch! I will update the docs based on that. Happy building 💪
