### ISSUE TITLE
Owner address =0 if you display 'My NFT's

### ISSUE THREAD

**Issue by ditholease** [chrisstef/polyplace#5]
Hi,
if you list your own NFT's, the adress is 0.

I changed the code to : 

{nft.seller =="0x0000000000000000000000000000000000000000" ? shortenAddress(currentAccount) : shortenAddress(nft.seller)}

this shows the correct owner adress.

in pages/nft-details.js

Cio

**Comment by chrisstef** [comment]
Issue can be closed. Thank you for the nice addition.✔💪

Here's the relevant MR:
https://github.com/chrisstef/polyplace/commit/a075a2f2e9d45b48bc8eec0008c3531399f88786
