### ISSUE TITLE
Fix bugs which result in endless loading state

### ISSUE THREAD

**Issue by chrisstef** [chrisstef/polyplace#9]
**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/86801f0c-a2cd-4d3d-bf54-1346b4488a23.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/9ce7837d-d1f9-4209-8c1e-7db07fe73ca9.png)

\-------------------------------------

**Website URL:**
[https://polyplace.vercel.app/](https://polyplace.vercel.app/)

**Device and browser info:**
Chrome 112.0.0.0 (1536x731) | Windows 10

**Date and time:**
April 30th 2023 | 2:02pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/d846dad6-808f-43ca-9d5a-acfa6ed56513](https://jam.dev/c/d846dad6-808f-43ca-9d5a-acfa6ed56513)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by devtayyab** [comment]
I created a new  PR by adding some error handling , this issue is resolved in that .
https://github.com/chrisstef/polyplace/pull/11

**Comment by chrisstef** [comment]
The PR is merged (https://github.com/chrisstef/polyplace/pull/11) 🙏
